name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23.0

    # TODO: get back
    # - name: Build
    #   run: go build -v ./*.go

    # - name: Build arts
    #   run: go build -v ./arts/*.go

    # - name: Test
    #   run: go test -v ./common/...
